# Generated by Django 3.2.25 on 2024-10-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_ball', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descriptions', models.TextField()),
                ('data_start', models.DateField()),
                ('data_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descriptions', models.TextField()),
                ('hack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.hack')),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeHack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('hack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.hack')),
            ],
        ),
    ]
