# Generated by Django 3.2.25 on 2024-10-04 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hack',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='criteria',
            name='hack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.hack'),
        ),
    ]
